export const ApiErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_FOUND: 'NOT_FOUND',
  SERVICE_SUSPENDED: 'SERVICE_SUSPENDED',
  SUBSCRIPTION_BLOCKED: 'SUBSCRIPTION_BLOCKED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  CONFIG_ERROR: 'CONFIG_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INITDATA_INVALID: 'INITDATA_INVALID',
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  MENU_SHIFT_CHECK_STALE: 'MENU_SHIFT_CHECK_STALE',
  MENU_ITEM_DELETE_BLOCKED_BY_FIXED_REWARD: 'MENU_ITEM_DELETE_BLOCKED_BY_FIXED_REWARD',
  PROMOTION_LIFECYCLE_STALE: 'PROMOTION_LIFECYCLE_STALE',
  STAFF_SHIFT_CANCELED_CONFLICT: 'STAFF_SHIFT_CANCELED_CONFLICT',
  STAFF_SHIFT_DATE_CONFLICT: 'STAFF_SHIFT_DATE_CONFLICT',
  STAFF_SHIFT_TODAY_OVERRIDE: 'STAFF_SHIFT_TODAY_OVERRIDE',
  STAFF_SHIFT_INVALID_INTERVAL: 'STAFF_SHIFT_INVALID_INTERVAL',
  STAFF_SHIFT_IMMUTABLE: 'STAFF_SHIFT_IMMUTABLE',
  STAFF_SHIFT_STALE: 'STAFF_SHIFT_STALE',
  STAFF_SHIFT_CONFIRMATION_STALE: 'STAFF_SHIFT_CONFIRMATION_STALE',
  STAFF_PROFILE_LINK_CONFLICT: 'STAFF_PROFILE_LINK_CONFLICT',
  STAFF_MODULE_SETTINGS_STALE: 'STAFF_MODULE_SETTINGS_STALE',
  STAFF_MODULE_DISABLED: 'STAFF_MODULE_DISABLED',
  TODAY_STAFF_SOURCE_SCHEDULE: 'TODAY_STAFF_SOURCE_SCHEDULE',
  VENUE_SCHEDULE_NOT_CONFIGURED: 'VENUE_SCHEDULE_NOT_CONFIGURED',
  VENUE_CLOSED_ON_SELECTED_DATE: 'VENUE_CLOSED_ON_SELECTED_DATE',
  VENUE_BOOKING_OUTSIDE_HOURS: 'VENUE_BOOKING_OUTSIDE_HOURS'
} as const

export type ApiErrorCode = (typeof ApiErrorCodes)[keyof typeof ApiErrorCodes]

export type ApiErrorEnvelope = {
  error?: {
    code?: string
    message?: string
    details?: unknown
  }
  requestId?: string
}

export type ApiErrorInfo = {
  status: number
  code?: string
  message?: string
  details?: unknown
  requestId?: string
}

export type ApiResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: ApiErrorInfo }

export const REQUEST_ID_HEADER = 'X-Request-Id'
