package com.hookah.platform.backend.telegram

import java.time.LocalDate

data class TableContext(
    val venueId: Long,
    val venueName: String,
    val tableId: Long,
    val tableNumber: Int,
    val tableToken: String,
    val staffChatId: Long?,
)

enum class StaffCallReason {
    COALS,
    BILL,
    COME,
    OTHER,
}

enum class BillPaymentMethod {
    CARD,
    CASH,
    UNKNOWN,
}

fun billPaymentMethodLabel(method: BillPaymentMethod): String =
    when (method) {
        BillPaymentMethod.CARD -> "Картой на месте"
        BillPaymentMethod.CASH -> "Наличными"
        BillPaymentMethod.UNKNOWN -> "Пока не знаю"
    }

enum class DialogStateType {
    NONE,
    QUICK_ORDER_WAIT_TEXT,
    QUICK_ORDER_WAIT_CONFIRM,
    STAFF_CALL_WAIT_COMMENT,
    GUEST_SUPPORT_WAIT_MESSAGE,
    BOT_JOIN_SHARED_WAIT_CODE,
    VENUE_CONNECT_WAIT_NAME,
    VENUE_CONNECT_WAIT_CITY,
    VENUE_CONNECT_WAIT_CONTACT_CHOICE,
    VENUE_CONNECT_WAIT_CONTACT,
    VENUE_CONNECT_WAIT_CONTACT_EXTRA,
    VENUE_CONNECT_WAIT_COMMENT,
    OWNER_VENUE_TERMS_WAIT_TRIAL_CUSTOM_DATE,
    OWNER_VENUE_TERMS_WAIT_CURRENT_PRICE,
    OWNER_VENUE_TERMS_WAIT_ZERO_PRICE_CONFIRM,
    OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE,
    OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE_DATE,
    OWNER_VENUE_TERMS_WAIT_NOTE,
    PLATFORM_SUBSCRIPTION_WAIT_CURRENT_PRICE,
    PLATFORM_SUBSCRIPTION_WAIT_ZERO_PRICE_CONFIRM,
    PLATFORM_SUBSCRIPTION_WAIT_FUTURE_PRICE,
    PLATFORM_SUBSCRIPTION_WAIT_FUTURE_PRICE_DATE,
    PLATFORM_VENUE_STATUS_WAIT_SUSPEND_REASON,
    OWNER_VENUE_PROFILE_WAIT_NAME,
    OWNER_VENUE_PROFILE_WAIT_CITY,
    OWNER_VENUE_PROFILE_WAIT_ADDRESS,
    OWNER_VENUE_PROFILE_WAIT_CONTACT,
    OWNER_VENUE_PROFILE_WAIT_CARD_DESCRIPTION,
    OWNER_VENUE_PROFILE_WAIT_HOURS_OPEN,
    OWNER_VENUE_PROFILE_WAIT_HOURS_CLOSE,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TITLE,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TEXT,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_MEDIA,
    OWNER_VENUE_ORDER_MENU_WAIT_SECTION_TITLE,
    OWNER_VENUE_ORDER_MENU_WAIT_SECTION_RENAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_NAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_RENAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE_EDIT,
    OWNER_VENUE_ORDER_MENU_WAIT_OPTION_NAME,
    OWNER_VENUE_TABLES_WAIT_NUMBER,
    OWNER_VENUE_TABLES_WAIT_CAPACITY,
    OWNER_VENUE_CREATE_WAIT_NAME,
    OWNER_VENUE_CREATE_WAIT_CITY,
    OWNER_VENUE_CREATE_WAIT_ADDRESS,
    OWNER_LIMIT_REQUEST_WAIT_COUNT,
    OWNER_LIMIT_REQUEST_WAIT_COMMENT,
    PLATFORM_LIMIT_REQUEST_WAIT_APPROVED_COUNT,
    VENUE_SETTINGS_WAIT_TIMEZONE,
    VENUE_STAFF_ORDERS_WAIT_BATCH_CANCEL_REASON,
    VENUE_STAFF_ORDERS_WAIT_ORDER_CANCEL_REASON,
    VENUE_STAFF_ORDERS_WAIT_ITEM_EXCLUDE_REASON,
    VENUE_STAFF_ORDERS_WAIT_ITEM_DISCOUNT_PERCENT,
    VENUE_BOOKING_WAIT_GUEST_MESSAGE,
    VENUE_BOOKING_CANCEL_WAIT_REASON,
    VENUE_BOOKING_HOLD_WAIT_CUSTOM_MINUTES,
    GUEST_BOOKING_WAIT_REPLY,
    GUEST_FEEDBACK_WAIT_COMMENT,
    STAFF_FEEDBACK_WAIT_REPLY,
    GUEST_FEEDBACK_WAIT_REPLY,
    VENUE_FEEDBACK_WAIT_PUBLIC_REVIEW_URL,
    VENUE_PROMOTION_WAIT_TITLE,
    VENUE_PROMOTION_WAIT_DESCRIPTION,
    VENUE_PROMOTION_WAIT_TERMS,
    VENUE_PROMOTION_WAIT_STARTS_AT,
    VENUE_PROMOTION_WAIT_ENDS_AT,
    VENUE_PROMOTION_WAIT_MEDIA,
    VENUE_PROMOTION_RULE_WAIT_PERCENT,
    VENUE_PROMOTION_RULE_WAIT_START_TIME,
    VENUE_PROMOTION_RULE_WAIT_END_TIME,
    PLATFORM_PROMOTION_PLACEMENT_WAIT_END_DATE,
    VENUE_LOYALTY_WAIT_CUSTOM_N,
    AI_WAIT_PROMOTION_TEXT_BRIEF,
    AI_WAIT_REVIEW_REPLY_BRIEF,
    AI_WAIT_BANNER_TEXT_BRIEF,
    GUEST_PROFILE_WAIT_NAME,
    GUEST_PROFILE_WAIT_BIRTHDAY,
    BOT_MENU_CART_WAIT_COMMENT,
}

data class DialogState(
    val state: DialogStateType,
    val payload: Map<String, String> = emptyMap(),
)

data class ResolvedChatContext(
    val table: TableContext,
    val userId: Long,
)

data class ActiveOrderSummary(
    val id: Long,
    val status: String,
    val displayNumber: Int? = null,
    val displayDate: LocalDate? = null,
)
