package com.hookah.platform.backend.telegram

import java.time.LocalDate

data class TableContext(
    val venueId: Long,
    val venueName: String,
    val tableId: Long,
    val tableNumber: Int,
    val tableToken: String,
    val staffChatId: Long?,
)

enum class StaffCallReason {
    COALS,
    BILL,
    COME,
    OTHER,
}

enum class DialogStateType {
    NONE,
    QUICK_ORDER_WAIT_TEXT,
    QUICK_ORDER_WAIT_CONFIRM,
    STAFF_CALL_WAIT_COMMENT,
    BOT_JOIN_SHARED_WAIT_CODE,
    VENUE_CONNECT_WAIT_NAME,
    VENUE_CONNECT_WAIT_CITY,
    VENUE_CONNECT_WAIT_CONTACT_CHOICE,
    VENUE_CONNECT_WAIT_CONTACT,
    VENUE_CONNECT_WAIT_CONTACT_EXTRA,
    VENUE_CONNECT_WAIT_COMMENT,
    OWNER_VENUE_TERMS_WAIT_TRIAL_CUSTOM_DATE,
    OWNER_VENUE_TERMS_WAIT_CURRENT_PRICE,
    OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE,
    OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE_DATE,
    OWNER_VENUE_TERMS_WAIT_NOTE,
    OWNER_VENUE_PROFILE_WAIT_NAME,
    OWNER_VENUE_PROFILE_WAIT_ADDRESS,
    OWNER_VENUE_PROFILE_WAIT_HOURS_OPEN,
    OWNER_VENUE_PROFILE_WAIT_HOURS_CLOSE,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TITLE,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TEXT,
    OWNER_VENUE_DESCRIPTION_WAIT_SECTION_MEDIA,
    OWNER_VENUE_ORDER_MENU_WAIT_SECTION_TITLE,
    OWNER_VENUE_ORDER_MENU_WAIT_SECTION_RENAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_NAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_RENAME,
    OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE_EDIT,
    OWNER_VENUE_ORDER_MENU_WAIT_OPTION_NAME,
    OWNER_VENUE_TABLES_WAIT_NUMBER,
    OWNER_VENUE_TABLES_WAIT_CAPACITY,
    VENUE_STAFF_ORDERS_WAIT_BATCH_CANCEL_REASON,
    VENUE_STAFF_ORDERS_WAIT_ORDER_CANCEL_REASON,
    VENUE_STAFF_ORDERS_WAIT_ITEM_EXCLUDE_REASON,
    VENUE_STAFF_ORDERS_WAIT_ITEM_DISCOUNT_PERCENT,
    BOT_MENU_CART_WAIT_COMMENT,
}

data class DialogState(
    val state: DialogStateType,
    val payload: Map<String, String> = emptyMap(),
)

data class ResolvedChatContext(
    val table: TableContext,
    val userId: Long,
)

data class ActiveOrderSummary(
    val id: Long,
    val status: String,
    val displayNumber: Int? = null,
    val displayDate: LocalDate? = null,
)
