package com.hookah.platform.backend.telegram.db

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import java.time.Instant
import java.util.concurrent.atomic.AtomicReference
import javax.sql.DataSource
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue

class StaffChatLinkCodeRepositoryTest {
    companion object {
        private lateinit var dataSource: HikariDataSource
        private var venueId: Long = 1L

        @BeforeAll
        @JvmStatic
        fun setup() {
            dataSource = HikariDataSource(
                HikariConfig().apply {
                    driverClassName = "org.h2.Driver"
                    jdbcUrl = "jdbc:h2:mem:staff_link_codes;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;INIT=CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE\\;CREATE DOMAIN IF NOT EXISTS JSONB AS JSON"
                    maximumPoolSize = 5
                }
            )
            createSchema(dataSource)
            seedData()
        }

        @AfterAll
        @JvmStatic
        fun tearDown() {
            dataSource.close()
        }

        private fun seedData() {
            dataSource.connection.use { connection ->
                connection.prepareStatement(
                    """
                        INSERT INTO users (telegram_user_id, username, first_name, last_name)
                        VALUES (1001, 'owner', 'Owner', 'One')
                    """.trimIndent()
                ).executeUpdate()
                connection.prepareStatement(
                    """
                        INSERT INTO venues (name, city, address, status)
                        VALUES ('Test Venue', 'City', 'Addr', 'active_published')
                    """.trimIndent(),
                    java.sql.Statement.RETURN_GENERATED_KEYS
                ).use { statement ->
                    statement.executeUpdate()
                    statement.generatedKeys.use { rs ->
                        rs.next()
                        venueId = rs.getLong(1)
                    }
                }
                connection.prepareStatement(
                    """
                        INSERT INTO venue_members (venue_id, user_id, role)
                        VALUES (?, 1001, 'OWNER')
                    """.trimIndent()
                ).use { insertMember ->
                    insertMember.setLong(1, venueId)
                    insertMember.executeUpdate()
                }
            }
        }

        private fun createSchema(dataSource: DataSource) {
            dataSource.connection.use { connection ->
                connection.createStatement().use { statement ->
                    statement.execute(
                        """
                            CREATE TABLE IF NOT EXISTS users (
                                telegram_user_id BIGINT PRIMARY KEY,
                                username TEXT NULL,
                                first_name TEXT NULL,
                                last_name TEXT NULL,
                                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                            )
                        """.trimIndent()
                    )
                    statement.execute(
                        """
                            CREATE TABLE IF NOT EXISTS venues (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name TEXT NOT NULL,
                                city TEXT NULL,
                                address TEXT NULL,
                                status TEXT NOT NULL,
                                features JSONB NULL,
                                ui_layout JSONB NULL,
                                staff_chat_id BIGINT NULL,
                                staff_chat_linked_at TIMESTAMP WITH TIME ZONE NULL,
                                staff_chat_linked_by_user_id BIGINT NULL,
                                staff_chat_unlinked_at TIMESTAMP WITH TIME ZONE NULL,
                                staff_chat_unlinked_by_user_id BIGINT NULL,
                                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                            )
                        """.trimIndent()
                    )
                    statement.execute(
                        """
                            CREATE TABLE IF NOT EXISTS venue_members (
                                venue_id BIGINT NOT NULL,
                                user_id BIGINT NOT NULL,
                                role TEXT NOT NULL,
                                PRIMARY KEY (venue_id, user_id)
                            )
                        """.trimIndent()
                    )
                    statement.execute(
                        """
                            CREATE TABLE IF NOT EXISTS telegram_staff_chat_link_codes (
                                code_hash TEXT PRIMARY KEY,
                                code_hint TEXT NULL,
                                venue_id BIGINT NOT NULL,
                                created_by_user_id BIGINT NULL,
                                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                revoked_at TIMESTAMP WITH TIME ZONE NULL,
                                used_at TIMESTAMP WITH TIME ZONE NULL,
                                used_by_user_id BIGINT NULL,
                                used_in_chat_id BIGINT NULL,
                                used_message_id BIGINT NULL
                            )
                        """.trimIndent()
                    )
                    statement.execute(
                        "CREATE UNIQUE INDEX IF NOT EXISTS uq_venues_staff_chat ON venues(staff_chat_id)"
                    )
                }
            }
        }
    }

    @BeforeEach
    fun cleanup() {
        dataSource.connection.use { connection ->
            connection.prepareStatement("TRUNCATE TABLE telegram_staff_chat_link_codes").executeUpdate()
            connection.prepareStatement("UPDATE venues SET staff_chat_id = NULL, staff_chat_linked_at = NULL").executeUpdate()
        }
    }

    @Test
    fun `createLinkCode revokes previous active codes`() = runBlocking {
        val nowRef = AtomicReference(Instant.now())
        val repository = StaffChatLinkCodeRepository(
            dataSource = dataSource,
            pepper = "pepper",
            ttlSeconds = 600,
            now = { nowRef.get() }
        )

        repository.createLinkCode(venueId = venueId, createdByUserId = 1001)!!
        repository.createLinkCode(venueId = venueId, createdByUserId = 1001)!!

        dataSource.connection.use { connection ->
            connection.prepareStatement(
                """
                    SELECT revoked_at IS NOT NULL AS revoked
                    FROM telegram_staff_chat_link_codes
                    ORDER BY created_at ASC
                """.trimIndent()
            ).use { statement ->
                statement.executeQuery().use { rs ->
                    rs.next()
                    assertTrue(rs.getBoolean("revoked"))
                    rs.next()
                    assertTrue(!rs.getBoolean("revoked"))
                }
            }
        }
    }

    @Test
    fun `consumeLinkCode marks used and prevents reuse`() = runBlocking {
        val repository = StaffChatLinkCodeRepository(
            dataSource = dataSource,
            pepper = "pepper",
            ttlSeconds = 600
        )
        val issued = repository.createLinkCode(venueId = venueId, createdByUserId = 1001)!!

        val success = repository.consumeLinkCode(
            code = issued.code,
            usedByUserId = 1001,
            chatId = -10,
            messageId = 1L
        ) { _, _ -> true }
        assertTrue(success is ConsumeResult.Success)

        val secondAttempt = repository.consumeLinkCode(
            code = issued.code,
            usedByUserId = 1001,
            chatId = -10,
            messageId = 2L
        ) { _, _ -> true }
        assertTrue(secondAttempt is ConsumeResult.InvalidOrExpired)

        dataSource.connection.use { connection ->
            connection.prepareStatement(
                "SELECT COUNT(*) FROM telegram_staff_chat_link_codes WHERE used_at IS NOT NULL"
            ).use { statement ->
                statement.executeQuery().use { rs ->
                    rs.next()
                    assertEquals(1, rs.getInt(1))
                }
            }
        }
    }

    @Test
    fun `expired code is rejected`() = runBlocking {
        val nowRef = AtomicReference(Instant.parse("2024-01-01T00:00:00Z"))
        val repository = StaffChatLinkCodeRepository(
            dataSource = dataSource,
            pepper = "pepper",
            ttlSeconds = 60,
            now = { nowRef.get() }
        )
        val issued = repository.createLinkCode(venueId = venueId, createdByUserId = 1001)!!
        nowRef.set(nowRef.get().plusSeconds(120))

        val result = repository.consumeLinkCode(
            code = issued.code,
            usedByUserId = 1001,
            chatId = -10,
            messageId = null
        ) { _, _ -> true }

        assertTrue(result is ConsumeResult.InvalidOrExpired)
    }
}
