ALTER TABLE promotion_rules
    DROP CONSTRAINT IF EXISTS promotion_rules_rule_type_check;

ALTER TABLE promotion_rules
    DROP CONSTRAINT IF EXISTS promotion_rules_discount_percent_check;

ALTER TABLE promotion_rules
    ADD CONSTRAINT IF NOT EXISTS promotion_rules_rule_type_check
    CHECK (rule_type IN ('HAPPY_HOURS_PERCENT', 'GIFT_WITH_ITEM', 'LOYALTY_NTH_HOOKAH'));

ALTER TABLE promotion_rules
    ADD CONSTRAINT IF NOT EXISTS promotion_rules_discount_percent_check
    CHECK (
        (rule_type = 'HAPPY_HOURS_PERCENT' AND discount_percent BETWEEN 1 AND 100)
        OR (rule_type IN ('GIFT_WITH_ITEM', 'LOYALTY_NTH_HOOKAH') AND discount_percent IS NULL)
    );

CREATE TABLE IF NOT EXISTS loyalty_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES loyalty_programs(id) ON DELETE CASCADE,
    venue_id BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(telegram_user_id) ON DELETE RESTRICT,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    batch_id BIGINT NOT NULL REFERENCES order_batches(id) ON DELETE CASCADE,
    order_batch_item_id BIGINT NOT NULL REFERENCES order_batch_items(id) ON DELETE CASCADE,
    order_promotion_application_id BIGINT NOT NULL REFERENCES order_promotion_applications(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL CHECK (status IN ('RESERVED', 'APPLIED', 'CANCELED')),
    discount_minor BIGINT NOT NULL CHECK (discount_minor >= 0),
    dedupe_key VARCHAR(180) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_program_user
    ON loyalty_redemptions (program_id, user_id, status);

CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_order
    ON loyalty_redemptions (order_id);

CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_batch
    ON loyalty_redemptions (batch_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_loyalty_redemptions_item_status
    ON loyalty_redemptions (order_batch_item_id, status);
