CREATE TABLE IF NOT EXISTS shift_extension_settings (
    venue_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    price_minor BIGINT,
    currency CHAR(3) NOT NULL DEFAULT 'RUB',
    max_extensions_per_session INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shift_extension_settings_venue FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    CONSTRAINT chk_shift_extension_settings_duration
        CHECK (duration_minutes > 0 AND duration_minutes <= 240),
    CONSTRAINT chk_shift_extension_settings_price
        CHECK (price_minor IS NULL OR price_minor >= 0),
    CONSTRAINT chk_shift_extension_settings_max
        CHECK (max_extensions_per_session IS NULL OR max_extensions_per_session > 0)
);

CREATE TABLE IF NOT EXISTS shift_extension_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    table_session_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    tab_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    duration_minutes INTEGER NOT NULL,
    price_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'RUB',
    current_orderable_until TIMESTAMP WITH TIME ZONE NOT NULL,
    requested_until TIMESTAMP WITH TIME ZONE NOT NULL,
    comment TEXT,
    idempotency_key TEXT,
    decided_by_user_id BIGINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    reject_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shift_extension_requests_venue FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    CONSTRAINT fk_shift_extension_requests_session FOREIGN KEY (table_session_id) REFERENCES table_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_shift_extension_requests_table FOREIGN KEY (table_id) REFERENCES venue_tables(id) ON DELETE RESTRICT,
    CONSTRAINT fk_shift_extension_requests_tab FOREIGN KEY (tab_id) REFERENCES tab(id) ON DELETE CASCADE,
    CONSTRAINT fk_shift_extension_requests_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT chk_shift_extension_requests_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_shift_extension_requests_duration
        CHECK (duration_minutes > 0 AND duration_minutes <= 240),
    CONSTRAINT chk_shift_extension_requests_price
        CHECK (price_minor >= 0)
);

CREATE INDEX IF NOT EXISTS idx_shift_extension_requests_pending_tab
    ON shift_extension_requests (table_session_id, tab_id, status);

CREATE INDEX IF NOT EXISTS idx_shift_extension_requests_idempotency
    ON shift_extension_requests (venue_id, table_session_id, requested_by_user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_shift_extension_requests_venue_status
    ON shift_extension_requests (venue_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_shift_extension_requests_order
    ON shift_extension_requests (order_id);

CREATE TABLE IF NOT EXISTS order_service_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    venue_id BIGINT NOT NULL,
    table_session_id BIGINT NOT NULL,
    tab_id BIGINT,
    source VARCHAR(32) NOT NULL,
    source_request_id BIGINT,
    label TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 1,
    unit_price_minor BIGINT NOT NULL,
    total_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'RUB',
    created_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_service_charges_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_service_charges_venue FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_service_charges_session FOREIGN KEY (table_session_id) REFERENCES table_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_service_charges_tab FOREIGN KEY (tab_id) REFERENCES tab(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_service_charges_request FOREIGN KEY (source_request_id)
        REFERENCES shift_extension_requests(id) ON DELETE SET NULL,
    CONSTRAINT chk_order_service_charges_source
        CHECK (source IN ('SHIFT_EXTENSION')),
    CONSTRAINT chk_order_service_charges_qty
        CHECK (qty > 0),
    CONSTRAINT chk_order_service_charges_amounts
        CHECK (unit_price_minor >= 0 AND total_minor >= 0),
    CONSTRAINT uq_order_service_charges_source_request UNIQUE (source, source_request_id)
);

CREATE INDEX IF NOT EXISTS idx_order_service_charges_order
    ON order_service_charges (order_id, created_at);
