ALTER TABLE order_batches
    ADD COLUMN rejected_reason_code VARCHAR(255) NULL;

ALTER TABLE order_batches
    ADD COLUMN rejected_reason_text VARCHAR(1000) NULL;

ALTER TABLE order_batches
    ADD COLUMN rejected_at TIMESTAMP WITH TIME ZONE NULL;

CREATE TABLE order_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    actor_user_id BIGINT NOT NULL REFERENCES users(telegram_user_id) ON DELETE CASCADE,
    actor_role VARCHAR(32) NOT NULL,
    action VARCHAR(64) NOT NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64) NULL,
    reason_text VARCHAR(1000) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_audit_order ON order_audit_log (order_id, created_at);
