CREATE TABLE IF NOT EXISTS telegram_inbound_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL UNIQUE,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload_json CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error CLOB,
    processed_at TIMESTAMP,
    next_attempt_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telegram_inbound_updates_status_next
    ON telegram_inbound_updates (status, next_attempt_at, received_at);
