ALTER TABLE IF EXISTS venue_booking_hours
    DROP CONSTRAINT IF EXISTS venue_booking_hours_time_check;

CREATE TABLE IF NOT EXISTS venue_booking_hours_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    opens_at TIME NOT NULL,
    closes_at TIME NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_booking_hours_overrides_venue FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    CONSTRAINT venue_booking_hours_overrides_venue_date_unique UNIQUE (venue_id, service_date)
);

CREATE INDEX IF NOT EXISTS idx_venue_booking_hours_overrides_venue_date
    ON venue_booking_hours_overrides (venue_id, service_date);
