CREATE TABLE IF NOT EXISTS venue_info_section_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    telegram_file_id VARCHAR(1024) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_info_section_media_section FOREIGN KEY (section_id) REFERENCES venue_info_sections(id) ON DELETE CASCADE,
    CONSTRAINT venue_info_section_media_type_check CHECK (media_type IN ('image', 'pdf'))
);

CREATE INDEX IF NOT EXISTS idx_venue_info_section_media_section_sort
    ON venue_info_section_media (section_id, sort_order, id);
