CREATE TABLE IF NOT EXISTS venue_booking_settings (
    venue_id BIGINT PRIMARY KEY,
    hold_minutes INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_venue_booking_settings_venue FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    CONSTRAINT venue_booking_settings_hold_minutes_check CHECK (hold_minutes IN (15, 30, 60))
);

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS arrival_deadline_at TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS seated_at TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS no_show_at TIMESTAMP WITH TIME ZONE NULL;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITH TIME ZONE NULL;
