EXECUTE IMMEDIATE (
    SELECT 'ALTER TABLE loyalty_programs DROP CONSTRAINT "' || constraint_name || '"'
    FROM information_schema.check_constraints
    WHERE constraint_schema = 'public'
      AND check_clause LIKE '%nth_value%'
    LIMIT 1
);

ALTER TABLE loyalty_programs
    ADD CONSTRAINT IF NOT EXISTS loyalty_programs_nth_value_range_check
    CHECK (nth_value BETWEEN 2 AND 50);

EXECUTE IMMEDIATE (
    SELECT 'ALTER TABLE loyalty_program_earn_targets DROP CONSTRAINT "' || constraint_name || '"'
    FROM information_schema.check_constraints
    WHERE constraint_schema = 'public'
      AND check_clause LIKE '%target_type%'
      AND check_clause LIKE '%CATEGORY_TYPE%'
    LIMIT 1
);

EXECUTE IMMEDIATE (
    SELECT 'ALTER TABLE loyalty_program_earn_targets DROP CONSTRAINT "' || constraint_name || '"'
    FROM information_schema.check_constraints
    WHERE constraint_schema = 'public'
      AND check_clause LIKE '%semantic_type%'
      AND check_clause LIKE '%HOOKAH%'
    LIMIT 1
);

DROP INDEX IF EXISTS uq_loyalty_program_earn_targets_program;

ALTER TABLE loyalty_program_earn_targets
    ALTER COLUMN semantic_type DROP NOT NULL;

ALTER TABLE loyalty_program_earn_targets
    ADD COLUMN IF NOT EXISTS menu_item_id BIGINT NULL REFERENCES menu_items(id) ON DELETE CASCADE;

ALTER TABLE loyalty_program_earn_targets
    ADD CONSTRAINT IF NOT EXISTS loyalty_program_earn_targets_target_type_check
    CHECK (target_type IN ('CATEGORY_TYPE', 'MENU_ITEM'));

ALTER TABLE loyalty_program_earn_targets
    ADD CONSTRAINT IF NOT EXISTS loyalty_program_earn_targets_semantic_type_check
    CHECK (semantic_type IS NULL OR semantic_type IN ('HOOKAH'));

ALTER TABLE loyalty_program_earn_targets
    ADD CONSTRAINT IF NOT EXISTS loyalty_program_earn_targets_shape_check
    CHECK (
        (target_type = 'CATEGORY_TYPE' AND semantic_type = 'HOOKAH' AND menu_item_id IS NULL)
        OR
        (target_type = 'MENU_ITEM' AND semantic_type IS NULL AND menu_item_id IS NOT NULL)
    );

CREATE INDEX IF NOT EXISTS idx_loyalty_program_earn_targets_program
    ON loyalty_program_earn_targets (program_id, target_type, semantic_type, menu_item_id);

CREATE TABLE IF NOT EXISTS loyalty_program_reward_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES loyalty_programs(id) ON DELETE CASCADE,
    target_type VARCHAR(32) NOT NULL CHECK (target_type IN ('CATEGORY_TYPE', 'MENU_ITEM')),
    semantic_type VARCHAR(32) NULL CHECK (semantic_type IS NULL OR semantic_type IN ('HOOKAH')),
    menu_item_id BIGINT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (target_type = 'CATEGORY_TYPE' AND semantic_type = 'HOOKAH' AND menu_item_id IS NULL)
        OR
        (target_type = 'MENU_ITEM' AND semantic_type IS NULL AND menu_item_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_loyalty_program_reward_targets_program
    ON loyalty_program_reward_targets (program_id, target_type, semantic_type, menu_item_id);

INSERT INTO loyalty_program_reward_targets (program_id, target_type, semantic_type)
SELECT lp.id, 'CATEGORY_TYPE', 'HOOKAH'
FROM loyalty_programs lp
WHERE NOT EXISTS (
    SELECT 1
    FROM loyalty_program_reward_targets lprt
    WHERE lprt.program_id = lp.id
);

ALTER TABLE telegram_dialog_state
    DROP CONSTRAINT IF EXISTS telegram_dialog_state_state_check;

ALTER TABLE telegram_dialog_state
    ADD CONSTRAINT telegram_dialog_state_state_check
        CHECK (
            state IN (
                'NONE',
                'QUICK_ORDER_WAIT_TEXT',
                'QUICK_ORDER_WAIT_CONFIRM',
                'STAFF_CALL_WAIT_COMMENT',
                'BOT_JOIN_SHARED_WAIT_CODE',
                'VENUE_CONNECT_WAIT_NAME',
                'VENUE_CONNECT_WAIT_CITY',
                'VENUE_CONNECT_WAIT_CONTACT_CHOICE',
                'VENUE_CONNECT_WAIT_CONTACT',
                'VENUE_CONNECT_WAIT_CONTACT_EXTRA',
                'VENUE_CONNECT_WAIT_COMMENT',
                'OWNER_VENUE_TERMS_WAIT_TRIAL_CUSTOM_DATE',
                'OWNER_VENUE_TERMS_WAIT_CURRENT_PRICE',
                'OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE',
                'OWNER_VENUE_TERMS_WAIT_FUTURE_PRICE_DATE',
                'OWNER_VENUE_TERMS_WAIT_NOTE',
                'OWNER_VENUE_PROFILE_WAIT_NAME',
                'OWNER_VENUE_PROFILE_WAIT_CITY',
                'OWNER_VENUE_PROFILE_WAIT_ADDRESS',
                'OWNER_VENUE_PROFILE_WAIT_CONTACT',
                'OWNER_VENUE_PROFILE_WAIT_CARD_DESCRIPTION',
                'OWNER_VENUE_PROFILE_WAIT_HOURS_OPEN',
                'OWNER_VENUE_PROFILE_WAIT_HOURS_CLOSE',
                'OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TITLE',
                'OWNER_VENUE_DESCRIPTION_WAIT_SECTION_TEXT',
                'OWNER_VENUE_DESCRIPTION_WAIT_SECTION_MEDIA',
                'OWNER_VENUE_ORDER_MENU_WAIT_SECTION_TITLE',
                'OWNER_VENUE_ORDER_MENU_WAIT_SECTION_RENAME',
                'OWNER_VENUE_ORDER_MENU_WAIT_ITEM_NAME',
                'OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE',
                'OWNER_VENUE_ORDER_MENU_WAIT_ITEM_RENAME',
                'OWNER_VENUE_ORDER_MENU_WAIT_ITEM_PRICE_EDIT',
                'OWNER_VENUE_ORDER_MENU_WAIT_OPTION_NAME',
                'OWNER_VENUE_TABLES_WAIT_NUMBER',
                'OWNER_VENUE_TABLES_WAIT_CAPACITY',
                'OWNER_VENUE_CREATE_WAIT_NAME',
                'OWNER_VENUE_CREATE_WAIT_CITY',
                'OWNER_VENUE_CREATE_WAIT_ADDRESS',
                'OWNER_LIMIT_REQUEST_WAIT_COUNT',
                'OWNER_LIMIT_REQUEST_WAIT_COMMENT',
                'PLATFORM_LIMIT_REQUEST_WAIT_APPROVED_COUNT',
                'VENUE_SETTINGS_WAIT_TIMEZONE',
                'VENUE_STAFF_ORDERS_WAIT_BATCH_CANCEL_REASON',
                'VENUE_STAFF_ORDERS_WAIT_ORDER_CANCEL_REASON',
                'VENUE_STAFF_ORDERS_WAIT_ITEM_EXCLUDE_REASON',
                'VENUE_STAFF_ORDERS_WAIT_ITEM_DISCOUNT_PERCENT',
                'VENUE_BOOKING_WAIT_GUEST_MESSAGE',
                'VENUE_BOOKING_CANCEL_WAIT_REASON',
                'VENUE_BOOKING_HOLD_WAIT_CUSTOM_MINUTES',
                'GUEST_BOOKING_WAIT_REPLY',
                'GUEST_FEEDBACK_WAIT_COMMENT',
                'STAFF_FEEDBACK_WAIT_REPLY',
                'GUEST_FEEDBACK_WAIT_REPLY',
                'VENUE_FEEDBACK_WAIT_PUBLIC_REVIEW_URL',
                'VENUE_PROMOTION_WAIT_TITLE',
                'VENUE_PROMOTION_WAIT_DESCRIPTION',
                'VENUE_PROMOTION_WAIT_TERMS',
                'VENUE_PROMOTION_WAIT_STARTS_AT',
                'VENUE_PROMOTION_WAIT_ENDS_AT',
                'VENUE_PROMOTION_WAIT_MEDIA',
                'VENUE_PROMOTION_RULE_WAIT_PERCENT',
                'VENUE_PROMOTION_RULE_WAIT_START_TIME',
                'VENUE_PROMOTION_RULE_WAIT_END_TIME',
                'PLATFORM_PROMOTION_PLACEMENT_WAIT_END_DATE',
                'GUEST_PROFILE_WAIT_NAME',
                'GUEST_PROFILE_WAIT_BIRTHDAY',
                'BOT_MENU_CART_WAIT_COMMENT',
                'VENUE_LOYALTY_WAIT_CUSTOM_N'
            )
        );
